### ISSUE TITLE
Cannot Authenticate

### ISSUE THREAD

**Issue by ngocnv1712** [ClassDo/classdo-js#101]
I have test authenticate with token bellow code:
const client = new ClassDoAPIClient({ apiKey: 'GENERATE_KEY' })
    console.log(client);
    client.viewer.get(['id'], { rooms: { fields: ['id', 'name'] }}).then(v => {
        console.log(v)
    })

but return error 403:
from origin 'http://localhost:9090' has been blocked by CORS policy: Response to preflight request doesn'

Please help me, thanks!

**Comment by joe-re** [comment]
@ngocnv1712 
Hi, thank you for your report.
Unfortunately for now classdo-js doesn't support used by browsers. And also you must not expose an API Key to browser side JavaScript because of security.
This is intended to be used on the server side, please take a look example here.
https://github.com/ClassDo/classdo-js/tree/master/example
Thanks.
